Move all exec scripts to a job

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -84,15 +84,6 @@ jobs:
           docker compose build
           docker compose up -d
 
-          echo docker container ls
-          echo "Run Laravel commands"
-          docker compose exec -T jobmosaic_app php artisan migrate --force
-          docker compose exec -T jobmosaic_app php artisan config:cache
-
-          echo "Install and build frontend"
-          docker compose exec -T jobmosaic_app npm ci
-          docker compose exec -T jobmosaic_app npm run build
-
           echo "Deployment completed successfully!"
           EOT
 
@@ -108,17 +99,23 @@ jobs:
             fi
           done
 
-      - name: Run Laravel commands
+      - name: Run Laravel and NPM commands
         run: |
-          for i in {1..10}; do
-            if ssh root@${{ env.SSH_HOST }} "docker-compose exec -T jobmosaic_app php artisan migrate --force"; then
-              echo "Laravel commands executed successfully."
-              break
-            else
-              echo "Waiting for jobmosaic_app to be ready for Laravel commands..."
-              sleep 10  # Wait for 10 seconds before trying again
-            fi
-          done
+          ssh root@${{ env.SSH_HOST }} << 'EOF'
+          set -e  # Exit immediately if a command exits with a non-zero status
+          echo "Running Laravel migrations..."
+          docker compose exec -T jobmosaic_app php artisan migrate --force
+          echo "Clearing cache..."
+          docker compose exec -T jobmosaic_app php artisan config:cache
+          docker compose exec -T jobmosaic_app php artisan route:cache
+          docker compose exec -T jobmosaic_app php artisan view:cache
+
+          echo "Installing NPM dependencies..."
+          docker compose exec -T jobmosaic_app npm ci
+
+          echo "Building the application..."
+          docker compose exec -T jobmosaic_app npm run build
+          EOF
 
       - name: Verify Deployment
         run: |
